insert into Usuarios (username, password, enabled) values ('manuel', '$2a$10$4oFz6dSoDWqotVBP.9rxxuL4H38wt.2v3H0yzGJM7EgyASQG.IJ8y', true);
insert into Usuarios (username, password, enabled) values ('juan', '$2a$10$PUu11HvrS1ua8kWHR38Ns.AKa.2bpqXG6uPhZpukWEoTZI0ZZIMRG', true);
insert into Usuarios (username, password, enabled) values ('pedro', '$2a$10$qFb3OlvHMFdE2.Z.Ue049eW07hhaFA/7/M86KtRL54HdTE6kFtKUm', true);

insert into Roles (nombre) values ('ROLE_ADMIN');
insert into Roles (nombre) values ('ROLE_USER');

insert into usuarios_roles (usuario_id, roles_id) values (1,1);
insert into usuarios_roles (usuario_id, roles_id) values (1,2);
insert into usuarios_roles (usuario_id, roles_id) values (2,1);

insert into Regiones (nombre) values ('North Korea');
insert into Regiones (nombre) values ('France');
insert into Regiones (nombre) values ('Poland');
insert into Regiones (nombre) values ('Russia');
insert into Regiones (nombre) values ('Philippines');
insert into Regiones (nombre) values ('China');
insert into Regiones (nombre) values ('Greece');
insert into Regiones (nombre) values ('Brazil');


insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Frants', 4, 'Jacobowicz', 'fjacobowicz0@t.co', '2021-08-09');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Karoline', 1, 'Grenkov', 'kgrenkov1@t-online.de', '2021-11-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Catha', 4, 'Warsap', 'cwarsap2@miibeian.gov.cn', '2021-09-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Angelika', 4, 'Onn', 'aonn3@ebay.co.uk', '2021-11-15');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Margarette', 1, 'Kinnett', 'mkinnett4@ox.ac.uk', '2021-02-01');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Benyamin', 3, 'Chishull', 'bchishull5@amazon.co.jp', '2021-04-27');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Woodrow', 4, 'Snellman', 'wsnellman6@ehow.com', '2021-05-07');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Carmon', 8, 'Delahunty', 'cdelahunty7@ucoz.com', '2021-04-29');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Dionis', 1, 'Benazet', 'dbenazet8@elegantthemes.com', '2021-09-28');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Jennica', 1, 'Brimilcome', 'jbrimilcome9@unc.edu', '2021-05-06');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Blayne', 6, 'Filyushkin', 'bfilyushkina@marriott.com', '2022-01-09');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Morty', 6, 'Germon', 'mgermonb@shinystat.com', '2021-09-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Luciana', 4, 'McFeate', 'lmcfeatec@dailymail.co.uk', '2021-09-14');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Ardyce', 2, 'Tigner', 'atignerd@parallels.com', '2022-01-04');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Zelma', 1, 'Cussins', 'zcussinse@ihg.com', '2021-02-25');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Sherry', 7, 'Caunt', 'scauntf@guardian.co.uk', '2021-09-21');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Darsie', 2, 'Weems', 'dweemsg@weebly.com', '2021-03-11');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Clemmie', 5, 'Chilvers', 'cchilversh@hhs.gov', '2021-04-02');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Brnaby', 3, 'Allot', 'balloti@alexa.com', '2021-11-05');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Lena', 5, 'Toovey', 'ltooveyj@nytimes.com', '2021-07-20');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Hastie', 4, 'Eisig', 'heisigk@free.fr', '2021-08-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Lissy', 7, 'Joselevitch', 'ljoselevitchl@netlog.com', '2021-08-05');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Mallorie', 5, 'Crystal', 'mcrystalm@cyberchimps.com', '2021-03-14');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Krishnah', 5, 'Palleske', 'kpallesken@qq.com', '2021-10-06');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Alexine', 7, 'Rosbrough', 'arosbrougho@chronoengine.com', '2021-10-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Cordelia', 4, 'Chivers', 'cchiversp@spotify.com', '2021-02-05');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Freedman', 8, 'Barkhouse', 'fbarkhouseq@fda.gov', '2021-04-04');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Edd', 1, 'Vidgen', 'evidgenr@networkadvertising.org', '2021-03-18');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Traci', 4, 'Tracy', 'ttracys@unc.edu', '2021-09-06');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Brinn', 7, 'Kidder', 'bkiddert@businessweek.com', '2021-07-13');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Fritz', 5, 'Ploughwright', 'fploughwrightu@dyndns.org', '2021-12-25');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Jens', 3, 'Lages', 'jlagesv@omniture.com', '2021-11-23');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Geoff', 2, 'Samsin', 'gsamsinw@bloglines.com', '2021-09-16');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Donal', 3, 'Messer', 'dmesserx@samsung.com', '2021-08-07');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Lorenza', 1, 'Bellow', 'lbellowy@fotki.com', '2021-02-26');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Maynord', 5, 'Hansford', 'mhansfordz@rediff.com', '2021-01-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Jonell', 4, 'Jaffray', 'jjaffray10@wp.com', '2021-09-16');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Sidnee', 3, 'Kidde', 'skidde11@boston.com', '2022-01-21');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Mort', 5, 'Bemrose', 'mbemrose12@ow.ly', '2022-01-05');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Tabina', 2, 'Largent', 'tlargent13@spiegel.de', '2021-07-20');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Blakelee', 2, 'Haney`', 'bhaney14@google.co.jp', '2022-01-01');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Gabbie', 1, 'Vasile', 'gvasile15@yahoo.com', '2021-07-19');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Dinnie', 1, 'Myhill', 'dmyhill16@japanpost.jp', '2021-12-15');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Jeanie', 1, 'Lax', 'jlax17@ftc.gov', '2021-08-08');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Frankie', 1, 'Steart', 'fsteart18@seesaa.net', '2022-01-18');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Wilie', 3, 'Anneslie', 'wanneslie19@mysql.com', '2021-07-26');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Lana', 3, 'Leman', 'lleman1a@taobao.com', '2021-06-06');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Nathalie', 7, 'Czyz', 'nczyz1b@qq.com', '2021-01-28');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Missy', 2, 'Gindghill', 'mgindghill1c@moonfruit.com', '2021-10-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Lane', 8, 'Trewhella', 'ltrewhella1d@vk.com', '2021-10-25');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Wendye', 4, 'Cyples', 'wcyples1e@salon.com', '2022-01-12');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Barry', 7, 'Caberas', 'bcaberas1f@i2i.jp', '2021-10-02');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Price', 7, 'Brazener', 'pbrazener1g@w3.org', '2021-10-13');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Rosalyn', 5, 'Blaxter', 'rblaxter1h@g.co', '2021-06-20');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Bran', 7, 'Fulham', 'bfulham1i@weebly.com', '2021-02-23');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Clementius', 2, 'Etchell', 'cetchell1j@skyrock.com', '2021-05-28');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Winifred', 2, 'Jaffray', 'wjaffray1k@reuters.com', '2021-02-13');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Darius', 8, 'De Robertis', 'dderobertis1l@uiuc.edu', '2021-04-05');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Hayyim', 5, 'Dmytryk', 'hdmytryk1m@icio.us', '2021-03-16');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Ely', 5, 'Clougher', 'eclougher1n@chicagotribune.com', '2021-12-04');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Teddie', 2, 'Dignon', 'tdignon1o@so-net.ne.jp', '2022-01-21');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Rose', 6, 'Guichard', 'rguichard1p@newsvine.com', '2021-02-22');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Rory', 4, 'Yosselevitch', 'ryosselevitch1q@exblog.jp', '2021-07-09');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Levey', 5, 'Clampe', 'lclampe1r@wsj.com', '2022-01-03');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Conrade', 6, 'Mulroy', 'cmulroy1s@scientificamerican.com', '2021-08-23');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Lorelle', 5, 'Digginson', 'ldigginson1t@skype.com', '2021-11-17');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Davie', 2, 'Rigeby', 'drigeby1u@fotki.com', '2021-10-03');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Alasdair', 1, 'Broadbere', 'abroadbere1v@indiatimes.com', '2021-12-08');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Jorgan', 2, 'O''Shields', 'joshields1w@nydailynews.com', '2021-11-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Saxe', 7, 'McKimm', 'smckimm1x@salon.com', '2021-06-06');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Iain', 3, 'Cornels', 'icornels1y@usatoday.com', '2022-01-18');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Kimberley', 6, 'Stow', 'kstow1z@w3.org', '2021-09-06');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Teresina', 5, 'Livsey', 'tlivsey20@wikimedia.org', '2021-10-26');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Jillene', 5, 'McKniely', 'jmckniely21@youku.com', '2021-08-26');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Adelheid', 1, 'Cunnington', 'acunnington22@imageshack.us', '2021-07-23');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Leoline', 5, 'Pollastrino', 'lpollastrino23@chron.com', '2021-03-20');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Edyth', 4, 'Noblett', 'enoblett24@163.com', '2021-06-21');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Lorianne', 1, 'Postins', 'lpostins25@jiathis.com', '2021-04-09');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Jaimie', 4, 'Dumini', 'jdumini26@forbes.com', '2021-12-16');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Sheila', 5, 'Bossom', 'sbossom27@cmu.edu', '2021-05-09');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Brande', 1, 'Gave', 'bgave28@dedecms.com', '2021-03-02');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Shelley', 5, 'Creany', 'screany29@archive.org', '2021-08-25');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Aubry', 6, 'Mulqueen', 'amulqueen2a@businessinsider.com', '2021-02-20');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Murdoch', 8, 'Stronge', 'mstronge2b@tinyurl.com', '2021-04-23');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Dulcea', 7, 'Bevir', 'dbevir2c@ovh.net', '2021-12-09');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Olin', 2, 'Wigglesworth', 'owigglesworth2d@columbia.edu', '2021-09-14');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Myrna', 1, 'Asel', 'masel2e@biblegateway.com', '2021-08-07');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Mavra', 7, 'Clinnick', 'mclinnick2f@jigsy.com', '2021-06-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Rollo', 4, 'Hilldrup', 'rhilldrup2g@biblegateway.com', '2021-09-30');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Ami', 7, 'Grimwade', 'agrimwade2h@google.com.br', '2021-09-06');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Ethelbert', 5, 'Hacard', 'ehacard2i@usatoday.com', '2021-11-04');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Estele', 8, 'Vedntyev', 'evedntyev2j@vkontakte.ru', '2021-04-05');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Tawnya', 2, 'Applewhaite', 'tapplewhaite2k@ibm.com', '2022-01-21');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Gabriel', 8, 'Roundtree', 'groundtree2l@yale.edu', '2021-04-03');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Cordie', 7, 'Kunkler', 'ckunkler2m@nationalgeographic.com', '2021-04-22');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Wilow', 8, 'Allington', 'wallington2n@mlb.com', '2021-09-27');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Harrison', 6, 'McFfaden', 'hmcffaden2o@skyrock.com', '2022-01-19');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Dylan', 4, 'Hesser', 'dhesser2p@jigsy.com', '2021-08-28');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Oswald', 4, 'Kiss', 'okiss2q@shareasale.com', '2021-05-14');
insert into Clientes (nombre, region_id, apellidos, email, fecha) values ('Ryon', 7, 'Grigoryov', 'rgrigoryov2r@microsoft.com', '2021-12-31');